# Generated by Django 4.2.6 on 2024-01-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Total', models.CharField(max_length=50)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
