# Generated by Django 4.2.6 on 2024-01-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Customer_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
