# Generated by Django 4.2.6 on 2024-01-31 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_remove_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='CustomerAddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='CustomerContact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='CustomerName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pet.customer'),
        ),
    ]
