# Generated by Django 4.2.6 on 2024-01-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
