# Generated by Django 4.2.6 on 2024-01-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CustomerAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='CustomerContact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
