# Generated by Django 4.2.6 on 2024-01-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_alter_order_customeraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Customer_id',
            field=models.CharField(max_length=50),
        ),
    ]
