# Generated by Django 4.2.6 on 2024-01-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_rename_order_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
