# Generated by Django 4.2.6 on 2024-02-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0014_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='Customer_id',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='Status',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
