# Generated by Django 4.2.6 on 2024-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_customer_order_customer_id_customer_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
